// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Hardcoded keys to force the connection to work
const SUPABASE_URL = 'https://femzrvriospdusyfzgto.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlbXpydnJpb3NwZHVzeWZ6Z3RvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUxNDgxMDQsImV4cCI6MjA5MDcyNDEwNH0.6DxA2nrNvWZ7bIVKCHxjKfuyC2xPM0wCN47GH9XKCN0';

// TRACKER: This proves the new code is live
console.log("🚨 TRACKER: THE HARDCODED KEYS ARE LIVE!");

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});